spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://8.129.45.134:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://8.129.45.134:8761/eureka/,http://8.129.45.134:8861/eureka/,http://8.129.45.134:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info