spring:
  application:
    name: itoken-service-redis
  boot:
    admin:
      client:
        url: http://8.129.45.134:8084
  zipkin:
    base-url: http://8.129.45.134:9411
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.131.129:26379,192.168.131.129:26380,192.168.131.129:26381

server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://8.129.45.134:8761/eureka/,http://8.129.45.134:8861/eureka/,http://8.129.45.134:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info