spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://8.129.45.134:8084
  zipkin:
    base-url: http://8.129.45.134:9411

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://8.129.45.134:8761/eureka/,http://8.129.45.134:8861/eureka/,http://8.129.45.134:8961/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info